name: Deploy

on:
  push:
    branches: ["main"]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm test

  deploy-site:
    needs: test
    runs-on: ubuntu-latest
    name: Deploy static site to Cloudflare
    environment:
      name: beta
      url: https://beta.taskplus.cc
    steps:
      - uses: actions/checkout@v4
      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
